"""
Austin 2-Step Dance Bot v2 — Headless, API-based
Scrapes today's dance events and sends a WhatsApp poll via Green API.

Usage:
    python bot.py                  # Scrape + send poll
    python bot.py --dry-run        # Scrape only, print what would be sent
    python bot.py --list-groups    # List all groups (to find your group ID)
"""
import asyncio
import json
import logging
import sys
from pathlib import Path

from scraper import scrape_today_events, format_poll_question
from whatsapp_api import GreenApiClient

CONFIG_PATH = Path(__file__).parent / "config.json"
LOG_PATH = Path(__file__).parent / "bot.log"

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(LOG_PATH),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)


def load_config() -> dict:
    with open(CONFIG_PATH) as f:
        return json.load(f)


async def main():
    dry_run = "--dry-run" in sys.argv
    list_groups = "--list-groups" in sys.argv

    config = load_config()
    instance_id = config.get("green_api_instance_id", "")
    api_token = config.get("green_api_token", "")
    group_id = config.get("group_id", "")

    if (not instance_id or not api_token) and not dry_run:
        print("ERROR: Edit config.json and set your Green API credentials.")
        print("  1. Sign up at https://console.green-api.com/")
        print("  2. Create an instance and link your WhatsApp number")
        print("  3. Copy instance_id and api_token to config.json")
        return

    client = GreenApiClient(instance_id, api_token)

    # List groups mode
    if list_groups:
        print("Fetching groups...")
        groups = client.list_groups()
        if not groups:
            print("No groups found. Is the bot's number in any groups?")
            return
        print(f"\nFound {len(groups)} groups:")
        for g in groups:
            name = g.get("name", g.get("contactName", "Unknown"))
            gid = g.get("id", "Unknown")
            print(f"  {name} — {gid}")
        print("\nCopy the group ID and paste it into config.json as 'group_id'.")
        return

    # Scrape events
    logger.info("Scraping today's events...")
    venues = await scrape_today_events()

    if not venues:
        logger.info("No venues with events found for today. Nothing to send.")
        return

    question, options = format_poll_question(venues)

    logger.info(f"Poll: {question}")
    for i, opt in enumerate(options, 1):
        logger.info(f"  {i}) {opt}")

    if dry_run:
        print("\n[DRY RUN] Poll not sent.")
        return

    if not group_id or group_id == "YOUR_GROUP_ID@g.us":
        print("ERROR: Edit config.json and set your group_id.")
        print("  Run: python bot.py --list-groups")
        return

    # Send poll
    logger.info(f"Sending poll to {group_id}...")
    result = client.send_poll(group_id, question, options)

    if "idMessage" not in result:
        logger.error(f"Poll failed: {result}")
        return

    # Send follow-up message
    follow_up = config.get("follow_up_message",
        "\U0001f97e\U0001f916 This poll was autogenerated by BootBot.\n"
        "See any issues? Comment below!"
    )
    client.send_message(group_id, follow_up)

    logger.info("Done!")


if __name__ == "__main__":
    asyncio.run(main())
