"""
Austin 2-Step Dance Bot v2 — Headless, API-based
Scrapes today's dance events and sends a WhatsApp poll via Green API.

Usage:
    python bot.py                       # Scrape + send poll
    python bot.py --dry-run             # Scrape only, print what would be sent
    python bot.py --list-groups         # List all groups (to find your group ID)
    python bot.py --preview-fact [date] # Preview today's (or a specific date's) trivia fact
"""
import asyncio
import json
import logging
import sys
from datetime import date
from pathlib import Path

import facts
from scraper import scrape_today_events, format_poll_question
from whatsapp_api import GreenApiClient

CONFIG_PATH = Path(__file__).parent / "config.json"
LOG_PATH = Path(__file__).parent / "bot.log"

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(LOG_PATH),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)


def load_config() -> dict:
    with open(CONFIG_PATH) as f:
        return json.load(f)


async def main():
    dry_run = "--dry-run" in sys.argv
    list_groups = "--list-groups" in sys.argv

    # --preview-fact [YYYY-MM-DD]  — short-circuit for testing trivia
    if "--preview-fact" in sys.argv:
        idx = sys.argv.index("--preview-fact")
        target = date.today()
        if idx + 1 < len(sys.argv) and not sys.argv[idx + 1].startswith("--"):
            target = date.fromisoformat(sys.argv[idx + 1])
        fact = facts.get_fact(target)
        if fact is None:
            print(f"No fact for {target}.")
        else:
            print(f"[{target}]")
            print(facts.format_fact(fact))
        return

    config = load_config()
    instance_id = config.get("green_api_instance_id", "")
    api_token = config.get("green_api_token", "")
    group_id = config.get("group_id", "")

    if (not instance_id or not api_token) and not dry_run:
        print("ERROR: Edit config.json and set your Green API credentials.")
        print("  1. Sign up at https://console.green-api.com/")
        print("  2. Create an instance and link your WhatsApp number")
        print("  3. Copy instance_id and api_token to config.json")
        return

    client = GreenApiClient(instance_id, api_token)

    # List groups mode
    if list_groups:
        print("Fetching groups...")
        groups = client.list_groups()
        if not groups:
            print("No groups found. Is the bot's number in any groups?")
            return
        print(f"\nFound {len(groups)} groups:")
        for g in groups:
            name = g.get("name", g.get("contactName", "Unknown"))
            gid = g.get("id", "Unknown")
            print(f"  {name} — {gid}")
        print("\nCopy the group ID and paste it into config.json as 'group_id'.")
        return

    # Scrape events
    logger.info("Scraping today's events...")
    venues = await scrape_today_events()

    if not venues:
        logger.info("No venues with events found for today. Nothing to send.")
        return

    question, option_chunks = format_poll_question(venues)

    for chunk_idx, options in enumerate(option_chunks):
        label = f" (part {chunk_idx + 1})" if len(option_chunks) > 1 else ""
        logger.info(f"Poll{label}: {question}")
        for i, opt in enumerate(options, 1 + chunk_idx * 12):
            logger.info(f"  {i}) {opt}")

    if dry_run:
        print("\n[DRY RUN] Poll not sent.")
        return

    if not group_id or group_id == "YOUR_GROUP_ID@g.us":
        print("ERROR: Edit config.json and set your group_id.")
        print("  Run: python bot.py --list-groups")
        return

    # Send poll(s)
    for chunk_idx, options in enumerate(option_chunks):
        label = f" (part {chunk_idx + 1})" if len(option_chunks) > 1 else ""
        poll_question = f"{question}{label}"
        logger.info(f"Sending poll{label} to {group_id}...")
        result = client.send_poll(group_id, poll_question, options)

        if "idMessage" not in result:
            logger.error(f"Poll{label} failed: {result}")
            return

    # Build the follow-up message: trivia fact + BootBot sign-off
    default_signoff = (
        "\U0001f97e\U0001f916 This poll and (hopefully correct) trivia was autogenerated by BootBot.\n"
        "See any issues? Comment below!\n"
        "Full calendar: https://austin2step.com/"
    )
    signoff = config.get("follow_up_message", default_signoff)

    fact = facts.get_fact()
    parts = []
    if fact is not None:
        parts.append(facts.format_fact(fact))
    parts.append(signoff)
    follow_up = "\n\n".join(parts)

    client.send_message(group_id, follow_up)

    logger.info("Done!")


if __name__ == "__main__":
    asyncio.run(main())
